mysite/bboard/urls.py
from django.urls import path


from .views import index,  user_is_activate, profile, billing_change, shop_view, shop_detail, checkout, shop_view_category,about,sendler
from .views import MyLoginView, MyLogoutView, ChangeUserView, DropPassword, RegisterDon,RegisterNewUserView

app_name = 'bboard'
urlpatterns = [
    path('about/', about, name='about'),
    path('accounts/profile/billing/', billing_change, name='billing'),
    path('accounts/profile/change/', ChangeUserView.as_view(), name='profile_change'),
    path('accounts/profile/',profile, name='profile'),
    
    path('accounts/register/activate/<str:sign>/', user_is_activate, name='register_activate'),
    path('accounts/register/don', RegisterDon.as_view() ,name='register_don'),
    path('accounts/register/', RegisterNewUserView.as_view() ,name='register'),

    path('accounts/logout/', MyLogoutView.as_view(), name='logout'),
    
    path('accounts/login/', MyLoginView.as_view(), name='login'),
    path('accounts/drop/',DropPassword.as_view(), name='drop'),
    path('accounts/checkout/', checkout, name='checkout'),
    path('sendler/', sendler, name='sendler'),
    path('shop/cat/<int:pk>/', shop_view_category, name='shop_cat'),
    path('shop/<slug:slug>/', shop_detail, name='shop_detail' ),
    path('shop/', shop_view, name='shop_view'),
    path('', index, name='index'),
]

mysite/cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = 'cart'
urlpatterns = [
    

    path('add/<int:product_id>/',cart_add,name='cart_add'),
    path('detail/',cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',cart_remove,name='cart_remove'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('bboard.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/bboard/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .apps import user_reg
from .models import AdvUser, UserData, SubCategory,SuperCategory,Product, EmailForSub

class ChangeUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='email')

    class Meta:
        model = AdvUser
        fields = ('username','email','send_messages')


class RegisterNewUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput, )
    passwordd = forms.CharField(label='Confirm password',  widget=forms.PasswordInput, )
    username = forms.CharField(label='Username', required=True)
    
    def clean_password1(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password
    def clean(self):
        super().clean()
        password = self.cleaned_data['password']
        passwordd = self.cleaned_data['passwordd']
        if password and passwordd and passwordd != password:
            errors = {'passwordd': ValidationError('Password don`t match.', code='password_mismatch')}
            raise ValidationError(errors)
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_activated=False
        user.is_active = False
        if commit:
            user.save()
        user_reg.send(RegisterNewUserForm,instance=user)
        return user
    
    class Meta:
        model = AdvUser
        fields = ('username','email','password', 'passwordd', 'send_messages')

class UserDataForm(forms.ModelForm):
    
    
    class Meta:
        model = UserData

    
        fields = ('name','phoneNumber','address','indexxx')

class UserDataForm(forms.ModelForm):
    
    
    class Meta:
        model = UserData

    
        fields = ('name','phoneNumber','address','indexxx')

class SubCategoryForm(forms.ModelForm):
    super_category= forms.ModelChoiceField(queryset=SuperCategory.objects.all(), empty_label=None, label='Category', required=False)

    class Meta:
        model = SubCategory
        fields = '__all__'

class ProductCategoryForm(forms.ModelForm):
    category= forms.ModelChoiceField(queryset=SubCategory.objects.all(), empty_label=None, label='Category', required=True)

    class Meta:
        model = Product
        fields = '__all__'

class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=40, label='',widget=forms.TextInput(attrs={'placeholder':'search'}))

class send_for_follow(forms.Form):
    message_for_fol = forms.CharField(required=True, max_length=1500,widget=forms.TextInput(attrs={'placeholder':'Message'}) )

class subscribeee(forms.ModelForm):
    emaill = forms.EmailField(label='Email',widget=forms.EmailInput(attrs={'placeholder':'write'}))
    class Meta:
        model = EmailForSub
        fields = '__all__'

class Oplata(forms.Form):
    cssd = forms.BooleanField(label='buy')

mysite/bboard/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse, reverse_lazy
from django.core.mail import send_mail

from mysite.settings import EMAIL_HOST
from .utilities import signer
from .models import AdvUser, UserData, Product, SubCategory,  EmailForSub, MainImage, Orderjj
from .forms import ChangeUserForm, RegisterNewUserForm, UserDataForm,  send_for_follow, Oplata
from cart.forms import CartAddProductForm
from cart.cart import Cart

def index(request):

    image = MainImage.objects.filter(in_jobs=True)
    product = Product.objects.filter(available=True)[:20]
    

    context = {'image':image,'product':product}
    
    
    

    return render(request,'main/index.html',context)



class MyLoginView(LoginView):

    template_name = 'main/users/login.html'
    def get_success_url(self):
        return reverse_lazy('bboard:profile')


@login_required
def profile(request):

    bb=UserData.objects.filter(pk=request.user.pk)
    
    context = {'bb':bb}

    return render(request, 'main/users/profile.html',context)

class MyLogoutView(LoginRequiredMixin, LogoutView):
    template_name='main/index.html'

class ChangeUserView(SuccessMessageMixin,LoginRequiredMixin,UpdateView):
    model = AdvUser
    template_name = 'main/users/change_user.html'
    form_class = ChangeUserForm
    success_url = reverse_lazy('bboard:profile')
    success_message = 'Data Change'
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    def get_object(self,queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class DropPassword(SuccessMessageMixin, PasswordChangeView):
    template_name = 'main/users/drop_password.html'
    success_url = reverse_lazy('bboard:profile')

class RegisterNewUserView(CreateView):
    model = AdvUser
    template_name = 'main/users/register.html'
    form_class = RegisterNewUserForm
    success_url = reverse_lazy('bboard:register_don')

class RegisterDon(TemplateView):
    template_name = 'main/users/register_don.html'

def user_is_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except:
        return render(request,'main/users/register_bed.html')
    user=get_object_or_404(AdvUser, username=username)
    user.is_activated=True
    user.is_active=True
    xxx=UserData(name=username, indexxx=' ', address=' ', phoneNumber=' ')
    xxx.save()
    user.save()
    return render(request, 'main/users/register_activate.html')
'''Редактирование записи в бд'''
@login_required
def billing_change(request):
    try:
        bb=UserData.objects.get(pk=request.user.pk)
    except UserData.DoesNotExist:
        bb = None

    
    if request.method == 'POST':
        bbf = UserDataForm(request.POST, instance=bb)
        if bbf.is_valid():
            bbf.save()
            return HttpResponseRedirect(reverse('bboard:profile'))
            
    else:
        bbf = UserDataForm(instance=bb)
        context = {'bbf':bbf}
        return render(request,'main/users/billing_change.html',context)




def shop_detail(request,slug):
    product = get_object_or_404(Product,  slug=slug, available=True)
    ais = product.additionalimage_set.all()
    cart_product_form = CartAddProductForm()
    context = {'product':product, 'ais':ais, 'cart_product_form':cart_product_form}
    return render(request,'main/single-product.html',context)

@login_required
def checkout(request):
    try:
        bb=UserData.objects.get(pk=request.user.pk)
    except UserData.DoesNotExist:
        bb = None




    
        
    if request.method == 'POST':
        bbf = UserDataForm(request.POST, instance=bb)

        cart = Cart(request)    
        
        if bbf.is_valid():
            bbf.save()
            xx = Orderjj.objects.create(name=bb.name, phoneNumber=bb.phoneNumber,address=bb.address,indexxx=bb.indexxx,total=cart.get_total_price())
            cart.clear()
            x =request.META.get('HTTP_REFERER')
            return redirect(x)
            
    else:
        cssd = Oplata()
        bbf = UserDataForm(instance=bb)
        context = {'bbf':bbf,'cssd':cssd}
        return render(request, 'main/checkout.html',context)

    
def shop_view(request):
    categories = SubCategory.objects.all().values('name','pk')
    product = Product.objects.filter(available=True)
    x = 0

    for i in product:  # счетчик выводимых записей
        x+=1
    if "keyword" in request.GET:
        keyword = request.GET['keyword']
        q = Q(name__icontains=keyword) | Q(description__icontains=keyword)
        product = product.filter(q)
    else:
        keyword = ''

    paginator = Paginator(product, 8)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'product': page.object_list, 'page':page,'x':x, 'categories':categories}
    return render(request, 'main/shop.html', context)

def shop_view_category(request, pk):
    category = get_object_or_404(SubCategory, pk=pk)
    product = Product.objects.filter(available=True, category=pk )
    categories = SubCategory.objects.all().values('name','pk')
    x = 0
    for i in product:  # счетчик выводимых записей
        x+=1
    if "keyword" in request.GET:
        keyword = request.GET['keyword']
        q = Q(name__icontains=keyword) | Q(description__icontains=keyword)
        product = product.filter(q)
    else:
        keyword = ''
    paginator = Paginator(product, 8)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'product': page.object_list, 'page':page,'x':x, 'category':category, 'categories':categories}
    return render(request, 'main/shop_category.html', context)
    

def sendler(request):
    emailfor = EmailForSub.objects.all()
    membersmail = AdvUser.objects.filter(send_messages=True)
    senddd = []
    for i in membersmail:
        senddd.append(i.email)
    for i in emailfor:
        if i.emaill not in senddd:
            senddd.append(i.emaill)


    if request.method == 'POST':
        csc_form = send_for_follow()
        
        hosttt = EMAIL_HOST
        if csc_form.is_valid():
            xx = csc_form.cleaned_data['message_for_fol']
            send_mail('Hust', str(xx),str(hosttt),senddd ,fail_silently=False)
            return redirect('bboard:index')
    else:
        csc_form = send_for_follow()




    context = {'csc_form': csc_form}
    return render(request,'main/users/sendler.html', context)

def about(request):
    return render(request,'main/about.html')

mysite/bboard/templates/main/about.html
{% extends 'layout/basic.html' %}
{% block title %}Change || Hurst {%endblock title%}
{% block content %}



			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>About</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>About</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

            
			    <h1></h1>
                <div class="login-area  pt-80 pb-80">
                    <div class="container">
                        <form action="#">	
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="customer-login text-left">
                                        {% for i in abouttttt %}
                                        <h4 class="title-1 title-border text-uppercase mb-30">{{i.text}}</h4>
                                    
                                        {% endfor %}
                                    </div>					
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/checkout.html
{% extends 'layout/basic.html' %}


{% block title %}Checkout || Hurst{% endblock title %}
{% block content %}
			<!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Checkout</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Checkout</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			<div class="shopping-cart-area  pt-80 pb-80">
				<div class="container">	
					<div class="row">
						<div class="col-lg-12">
							<div class="shopping-cart">
								<!-- Nav tabs -->
								<ul class="cart-page-menu nav row clearfix mb-30">
									<li><a href="#shopping-cart" data-bs-toggle="tab">shopping cart</a></li>

									<li><a class="active"  href="#check-out" data-bs-toggle="tab">check out</a></li>
									<li><a href="#order-complete" data-bs-toggle="tab">order complete</a></li>
								</ul>

								<!-- Tab panes -->
								<div class="tab-content">
									<!-- shopping-cart start -->
									<div class="tab-pane " id="shopping-cart">
										<form action="#">
											<div class="shop-cart-table">
												<div class="table-content table-responsive">
													<table>
														<thead>
															<tr>
																<th class="product-thumbnail">Product</th>
																<th class="product-price">Price</th>
																<th class="product-quantity">Quantity</th>
																<th class="product-subtotal">Total</th>
																<th class="product-remove">Remove</th>
															</tr>
														</thead>
														
														
														
														<tbody>
                                                            {% for item in cart %}
														    {% with product=item.product %}
															<tr>
																<td class="product-thumbnail  text-left">
																	<!-- Single-product start -->
																	<div class="single-product">
																		<div class="product-img">
																			<a href="{% url 'bboard:shop_detail' slug=product.slug %}"><img src="{{product.image.url}}" alt="" /></a>
																		</div>
																		<div class="product-info">
																			<h4 class="post-title"><a class="text-light-black" href="{% url 'bboard:shop_detail' slug=product.slug %}">{{ product.name }}</a></h4>
																			
																		</div>
																	</div>
																	<!-- Single-product end -->												
																</td>
																<td class="product-price">${{ product.price }}</td>
																<td class="product-quantity">


																			<h6>{{ item.quantity }}</h6>

																		

																</td>
																<td class="product-subtotal">${{ item.total_price }}</td>
																<td class="product-remove">
																	<a href="{% url 'cart:cart_remove' product.id %}"><i class="zmdi zmdi-close"></i></a>
																</td>
															</tr>
															
															{% endwith %}
														    {% endfor %}
														</tbody>
													</table>
												</div>
											</div>
											
											<div class="row">
												
												<div class="col-md-6">
													<div class="customer-login payment-details mt-30">
														<h4 class="title-1 title-border text-uppercase">payment details</h4>
														<table>
															<tbody>
																{% for item in cart %}
															{% with product=item.product %}
															<tr>
																<td class="text-left">{{ product.name }} x {{item.quantity}}</td>
																<td class="text-end">${{item.total_price}}</td>
															</tr>
															
															
															{%endwith%}
															{% endfor %}
															<tr>
																<td class="text-left">Order Total</td>
																<td class="text-end">${{cart.get_total_price}}</td>
															</tr>
															</tbody>
														</table>
													</div>
												</div>
											</div>
											
										</form>		
									</div>
									<!-- shopping-cart end -->
									<!-- check-out start -->
									<div class="tab-pane active" id="check-out">
										
											<div class="shop-cart-table check-out-wrap">
												<div class="row">
													<div class="col-md-6">
														<div class="billing-details pr-20">
															<h4 class="title-1 title-border text-uppercase mb-30">billing details</h4>
															
															<form method='post'>
																{%csrf_token%}
																{{bbf.as_p}}
																<button type="submit" data-text="buy" class="button-one submit-button mt-15">buy</button>
															</form>	
														</div>
													</div>
													
													<div class="col-md-6">
														<div class="our-order payment-details mt-60 pr-20">
															<h4 class="title-1 title-border text-uppercase mb-30">our order</h4>
															<table>
																<thead>
																	<tr>
																		<th><strong>Product</strong></th>
																		<th class="text-end"><strong>Total</strong></th>
																	</tr>
																</thead>
																<tbody>
																	{% for item in cart %}
																{% with product=item.product %}
																<tr>
																	<td class="text-left">{{ product.name }} x {{item.quantity}}</td>
																	<td class="text-end">${{item.total_price}}</td>
																</tr>
																
																
																{%endwith%}
																{% endfor %}
																<tr>
																	<td class="text-left">Order Total</td>
																	<td class="text-end">${{cart.get_total_price}}</td>
																</tr>
																</tbody>
															</table>
														</div>
													</div>
													
												</div>
											</div>
																					
									</div>
									<!-- check-out end -->
									
									<!-- order-complete start -->
									<div class="tab-pane" id="order-complete">
										<form action="#">
											<div class="thank-recieve bg-white mb-30">
												<p>Thank you. Your order has been received.</p>
											</div>
											<div class="order-info bg-white text-center clearfix mb-30">
												<div class="single-order-info">
													<h4 class="title-1 text-uppercase text-light-black mb-0">order no</h4>
													<p class="text-uppercase text-light-black mb-0"><strong>m 2653257</strong></p>
												</div>
												<div class="single-order-info">
													<h4 class="title-1 text-uppercase text-light-black mb-0">Date</h4>
													<p class="text-uppercase text-light-black mb-0"><strong>june 15, 2021</strong></p>
												</div>
												<div class="single-order-info">
													<h4 class="title-1 text-uppercase text-light-black mb-0">Total</h4>
													<p class="text-uppercase text-light-black mb-0"><strong>$ {{xxx.total}}</strong></p>
												</div>
												<div class="single-order-info">
													<h4 class="title-1 text-uppercase text-light-black mb-0">payment method</h4>
													<p class="text-uppercase text-light-black mb-0"><a href="#"><strong>check payment</strong></a></p>
												</div>
											</div>
											
										</form>										
									</div>
									<!-- order-complete end -->
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
	
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
				<!-- Footer-area start -->
				{% endblock content %}

mysite/bboard/templates/main/shop.html
{% extends 'layout/basic.html' %}

{%block title%} Shop {%endblock title%}
		
{%block content%}
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Shop</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Shop</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- PRODUCT-AREA START -->
			<div class="product-area pt-80 pb-80 product-style-2">
				<div class="container">
					<!-- Shop-Content End -->
					<div class="shop-content">
						<div class="row">
							<div class="col-md-12">
								<div class="product-option mb-30 clearfix">
									<!-- Categories start -->
									<div class="dropdown floatleft">
										<button class="option-btn" >
										Categories
										</button>
										<div class="dropdown-menu dropdown-width" >
											<!-- Widget-Categories start -->
											<aside class="widget widget-categories">
												<div class="widget-title">
													<h4>Categories</h4>
												</div>
												<div id="cat-treeview"  class="widget-info product-cat boxscrol2">
													<ul>
														{% for i in categories %}
														<a href="{% url 'bboard:shop_cat' pk=i.pk %}"><li><span>{{i.name}}</span>
														</li></a>
														{% endfor %}
														
													</ul>
												</div>
											</aside>
											<!-- Widget-categories end -->
										</div>
									</div>	
									<!-- Categories end -->
									
																
									<div class="showing text-end">
										<p class="mb-0 d-none d-md-block">Showing {{product.count}} of {{x}} Results</p>
									</div>
								</div>						
							</div>	
							<div class="col-md-12">
								<div class="row">
									<!-- Single-product start -->
									{% for i in product %}
									<div class="col-xl-3 col-md-4">
										<div class="single-product">
											<div class="product-img">
                                                {% if i.sale %}
												    <span class="pro-label new-label">Sale</span>
												{% endif %}
												<span class="pro-price-2">$ {{ i.price}}</span>
												<a href="{% url 'bboard:shop_detail' slug=i.slug %}"><img src="{{ i.image}}" alt="" /></a>
											</div>
											<div class="product-info clearfix text-center">
												<div class="fix">
													<h4 class="post-title"><a href="{% url 'bboard:shop_detail' slug=i.slug %}">{{i.name}}</a></h4>
												</div>
												
												
											</div>
										</div>
									</div>
									{% endfor %}
									<!-- Single-product end -->
								</div>
							</div>
							<div class="col-md-12">
								<!-- Pagination start -->
								<div class="shop-pagination  text-center">
									<div class="pagination">
										<ul>
											{% if page.has_previous %}
											    <li><a href="?page={{page.previous_page_number}}"><i class="zmdi zmdi-long-arrow-left"></i></a></li>
											{% endif %}

											<li><a class="active" href="#">{{page.number}} of {{page.paginator.num_pages}}</a></li>
											
											{% if page.has_next %}
											<li><a href="?page={{page.next_page_number}}"><i class="zmdi zmdi-long-arrow-right"></i></a></li>
											{% endif %}
										</ul>
									</div>
								</div>
								<!-- Pagination end -->
							</div>
						</div>
					</div>
					<!-- Shop-Content End -->
				</div>
			</div>
			<!-- PRODUCT-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content%}

mysite/bboard/templates/main/shop_category.html
{% extends 'layout/basic.html' %}

{%block title%} Shop {%endblock title%}
		
{%block content%}
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Shop</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Shop</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- PRODUCT-AREA START -->
			<div class="product-area pt-80 pb-80 product-style-2">
				<div class="container">
					<!-- Shop-Content End -->
					<div class="shop-content">
						<div class="row">
							<div class="col-md-12">
								<div class="product-option mb-30 clearfix">
									<!-- Categories start -->
									<div class="dropdown floatleft">
										<button class="option-btn" >
										Categories
										</button>
										<div class="dropdown-menu dropdown-width" >
											<!-- Widget-Categories start -->
											<aside class="widget widget-categories">
												<div class="widget-title">
													<h4>Categories</h4>
												</div>
												<div id="cat-treeview"  class="widget-info product-cat boxscrol2">
													<ul>
                                                        <a href="{% url 'bboard:shop_view' %}"><li><span>All</span>
														</li></a>
														{% for i in categories %}
														<a href="{% url 'bboard:shop_cat' pk=i.pk %}"><li><span>{{i.name}}</span>
														</li></a>
														{% endfor %}
														
													</ul>
												</div>
											</aside>
											<!-- Widget-categories end -->
										</div>
									</div>	
									<!-- Categories end -->
									
																
									<div class="showing text-end">
										<p class="mb-0 d-none d-md-block">Showing {{product.count}} of {{x}} Results</p>
									</div>
								</div>						
							</div>	
							<div class="col-md-12">
								<div class="row">
									<!-- Single-product start -->
									{% for i in product %}
									<div class="col-xl-3 col-md-4">
										<div class="single-product">
											<div class="product-img">
                                                {% if i.sale %}
												    <span class="pro-label new-label">Sale</span>
												{% endif %}
												<span class="pro-price-2">$ {{ i.price}}</span>
												<a href="{% url 'bboard:shop_detail' slug=i.slug %}"><img src="{{ i.image.url }}" alt="" /></a>
											</div>
											<div class="product-info clearfix text-center">
												<div class="fix">
													<h4 class="post-title"><a href="{% url 'bboard:shop_detail' slug=i.slug %}">{{i.name}}</a></h4>
												</div>
												
												
											</div>
										</div>
									</div>
									{% endfor %}
									<!-- Single-product end -->
								</div>
							</div>
							<div class="col-md-12">
								<!-- Pagination start -->
								<div class="shop-pagination  text-center">
									<div class="pagination">
										<ul>
											{% if page.has_previous %}
											    <li><a href="?page={{page.previous_page_number}}"><i class="zmdi zmdi-long-arrow-left"></i></a></li>
											{% endif %}

											<li><a class="active" href="#">{{page.number}} of {{page.paginator.num_pages}}</a></li>
											
											{% if page.has_next %}
											<li><a href="?page={{page.next_page_number}}"><i class="zmdi zmdi-long-arrow-right"></i></a></li>
											{% endif %}
										</ul>
									</div>
								</div>
								<!-- Pagination end -->
							</div>
						</div>
					</div>
					<!-- Shop-Content End -->
				</div>
			</div>
			<!-- PRODUCT-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content%}