mysite/bboard/urls.py
from django.urls import path


from .views import index,  user_is_activate, profile, billing_change, shop_view, shop_detail, checkout, shop_view_category,about,sendler
from .views import MyLoginView, MyLogoutView, ChangeUserView, DropPassword, RegisterDon,RegisterNewUserView

app_name = 'bboard'
urlpatterns = [
    path('about/', about, name='about'),
    path('accounts/profile/billing/', billing_change, name='billing'),
    path('accounts/profile/change/', ChangeUserView.as_view(), name='profile_change'),
    path('accounts/profile/',profile, name='profile'),
    
    path('accounts/register/activate/<str:sign>/', user_is_activate, name='register_activate'),
    path('accounts/register/don', RegisterDon.as_view() ,name='register_don'),
    path('accounts/register/', RegisterNewUserView.as_view() ,name='register'),

    path('accounts/logout/', MyLogoutView.as_view(), name='logout'),
    
    path('accounts/login/', MyLoginView.as_view(), name='login'),
    path('accounts/drop/',DropPassword.as_view(), name='drop'),
    path('accounts/checkout/', checkout, name='checkout'),
    path('sendler/', sendler, name='sendler'),
    path('shop/cat/<int:pk>/', shop_view_category, name='shop_cat'),
    path('shop/<slug:slug>/', shop_detail, name='shop_detail' ),
    path('shop/', shop_view, name='shop_view'),
    path('', index, name='index'),
]

mysite/cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

app_name = 'cart'
urlpatterns = [
    

    path('add/<int:product_id>/',cart_add,name='cart_add'),
    path('detail/',cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/',cart_remove,name='cart_remove'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('', include('bboard.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/bboard/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .apps import user_reg
from .models import AdvUser, UserData, SubCategory,SuperCategory,Product, EmailForSub

class ChangeUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='email')

    class Meta:
        model = AdvUser
        fields = ('username','email','send_messages')


class RegisterNewUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput, )
    passwordd = forms.CharField(label='Confirm password',  widget=forms.PasswordInput, )
    username = forms.CharField(label='Username', required=True)
    
    def clean_password1(self):
        password = self.cleaned_data['password']
        if password:
            password_validation.validate_password(password)
        return password
    def clean(self):
        super().clean()
        password = self.cleaned_data['password']
        passwordd = self.cleaned_data['passwordd']
        if password and passwordd and passwordd != password:
            errors = {'passwordd': ValidationError('Password don`t match.', code='password_mismatch')}
            raise ValidationError(errors)
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_activated=False
        user.is_active = False
        if commit:
            user.save()
        user_reg.send(RegisterNewUserForm,instance=user)
        return user
    
    class Meta:
        model = AdvUser
        fields = ('username','email','password', 'passwordd', 'send_messages')

class UserDataForm(forms.ModelForm):
    
    
    class Meta:
        model = UserData

    
        fields = ('name','phoneNumber','address','indexxx')

class UserDataForm(forms.ModelForm):
    
    
    class Meta:
        model = UserData

    
        fields = ('name','phoneNumber','address','indexxx')

class SubCategoryForm(forms.ModelForm):
    super_category= forms.ModelChoiceField(queryset=SuperCategory.objects.all(), empty_label=None, label='Category', required=False)

    class Meta:
        model = SubCategory
        fields = '__all__'

class ProductCategoryForm(forms.ModelForm):
    category= forms.ModelChoiceField(queryset=SubCategory.objects.all(), empty_label=None, label='Category', required=True)

    class Meta:
        model = Product
        fields = '__all__'

class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=40, label='',widget=forms.TextInput(attrs={'placeholder':'search'}))

class send_for_follow(forms.Form):
    message_for_fol = forms.CharField(required=True, max_length=1500,widget=forms.TextInput(attrs={'placeholder':'Message'}) )

class subscribeee(forms.ModelForm):
    emaill = forms.EmailField(label='Email',widget=forms.EmailInput(attrs={'placeholder':'write'}))
    class Meta:
        model = EmailForSub
        fields = '__all__'

class Oplata(forms.Form):
    cssd = forms.BooleanField(label='buy')

mysite/bboard/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.views.generic.base import TemplateView
from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse, reverse_lazy
from django.core.mail import send_mail

from mysite.settings import EMAIL_HOST
from .utilities import signer
from .models import AdvUser, UserData, Product, SubCategory,  EmailForSub, MainImage, Orderjj
from .forms import ChangeUserForm, RegisterNewUserForm, UserDataForm,  send_for_follow, Oplata
from cart.forms import CartAddProductForm
from cart.cart import Cart

def index(request):

    image = MainImage.objects.filter(in_jobs=True)
    product = Product.objects.filter(available=True)[:20]
    

    context = {'image':image,'product':product}
    
    
    

    return render(request,'main/index.html',context)



class MyLoginView(LoginView):

    template_name = 'main/users/login.html'
    def get_success_url(self):
        return reverse_lazy('bboard:profile')


@login_required
def profile(request):

    bb=UserData.objects.filter(pk=request.user.pk)
    
    context = {'bb':bb}

    return render(request, 'main/users/profile.html',context)

class MyLogoutView(LoginRequiredMixin, LogoutView):
    template_name='main/index.html'

class ChangeUserView(SuccessMessageMixin,LoginRequiredMixin,UpdateView):
    model = AdvUser
    template_name = 'main/users/change_user.html'
    form_class = ChangeUserForm
    success_url = reverse_lazy('bboard:profile')
    success_message = 'Data Change'
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)
    def get_object(self,queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

class DropPassword(SuccessMessageMixin, PasswordChangeView):
    template_name = 'main/users/drop_password.html'
    success_url = reverse_lazy('bboard:profile')

class RegisterNewUserView(CreateView):
    model = AdvUser
    template_name = 'main/users/register.html'
    form_class = RegisterNewUserForm
    success_url = reverse_lazy('bboard:register_don')

class RegisterDon(TemplateView):
    template_name = 'main/users/register_don.html'

def user_is_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except:
        return render(request,'main/users/register_bed.html')
    user=get_object_or_404(AdvUser, username=username)
    user.is_activated=True
    user.is_active=True
    xxx=UserData(name=username, indexxx=' ', address=' ', phoneNumber=' ')
    xxx.save()
    user.save()
    return render(request, 'main/users/register_activate.html')
'''Редактирование записи в бд'''
@login_required
def billing_change(request):
    try:
        bb=UserData.objects.get(pk=request.user.pk)
    except UserData.DoesNotExist:
        bb = None

    
    if request.method == 'POST':
        bbf = UserDataForm(request.POST, instance=bb)
        if bbf.is_valid():
            bbf.save()
            return HttpResponseRedirect(reverse('bboard:profile'))
            
    else:
        bbf = UserDataForm(instance=bb)
        context = {'bbf':bbf}
        return render(request,'main/users/billing_change.html',context)




def shop_detail(request,slug):
    product = get_object_or_404(Product,  slug=slug, available=True)
    ais = product.additionalimage_set.all()
    cart_product_form = CartAddProductForm()
    context = {'product':product, 'ais':ais, 'cart_product_form':cart_product_form}
    return render(request,'main/single-product.html',context)

@login_required
def checkout(request):
    try:
        bb=UserData.objects.get(pk=request.user.pk)
    except UserData.DoesNotExist:
        bb = None




    
        
    if request.method == 'POST':
        bbf = UserDataForm(request.POST, instance=bb)

        cart = Cart(request)    
        
        if bbf.is_valid():
            bbf.save()
            xx = Orderjj.objects.create(name=bb.name, phoneNumber=bb.phoneNumber,address=bb.address,indexxx=bb.indexxx,total=cart.get_total_price())
            cart.clear()
            x =request.META.get('HTTP_REFERER')
            return redirect(x)
            
    else:
        cssd = Oplata()
        bbf = UserDataForm(instance=bb)
        context = {'bbf':bbf,'cssd':cssd}
        return render(request, 'main/checkout.html',context)

    
def shop_view(request):
    categories = SubCategory.objects.all().values('name','pk')
    product = Product.objects.filter(available=True)
    x = 0

    for i in product:  # счетчик выводимых записей
        x+=1
    if "keyword" in request.GET:
        keyword = request.GET['keyword']
        q = Q(name__icontains=keyword) | Q(description__icontains=keyword)
        product = product.filter(q)
    else:
        keyword = ''

    paginator = Paginator(product, 8)

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'product': page.object_list, 'page':page,'x':x, 'categories':categories}
    return render(request, 'main/shop.html', context)

def shop_view_category(request, pk):
    category = get_object_or_404(SubCategory, pk=pk)
    product = Product.objects.filter(available=True, category=pk )
    categories = SubCategory.objects.all().values('name','pk')
    x = 0
    for i in product:  # счетчик выводимых записей
        x+=1
    if "keyword" in request.GET:
        keyword = request.GET['keyword']
        q = Q(name__icontains=keyword) | Q(description__icontains=keyword)
        product = product.filter(q)
    else:
        keyword = ''
    paginator = Paginator(product, 8)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {'product': page.object_list, 'page':page,'x':x, 'category':category, 'categories':categories}
    return render(request, 'main/shop_category.html', context)
    

def sendler(request):
    emailfor = EmailForSub.objects.all()
    membersmail = AdvUser.objects.filter(send_messages=True)
    senddd = []
    for i in membersmail:
        senddd.append(i.email)
    for i in emailfor:
        if i.emaill not in senddd:
            senddd.append(i.emaill)


    if request.method == 'POST':
        csc_form = send_for_follow()
        
        hosttt = EMAIL_HOST
        if csc_form.is_valid():
            xx = csc_form.cleaned_data['message_for_fol']
            send_mail('Hust', str(xx),str(hosttt),senddd ,fail_silently=False)
            return redirect('bboard:index')
    else:
        csc_form = send_for_follow()




    context = {'csc_form': csc_form}
    return render(request,'main/users/sendler.html', context)

def about(request):
    return render(request,'main/about.html')

mysite/bboard/templates/main/users/billing_change.html
{% extends 'layout/basic.html' %}
{% block title %} My Account || Hurst {% endblock title %}

{% block content %}
			<!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								{% for b in bb %}
								<div class="heading-banner-title">
									<h2>My Account</h2>
								</div>
								{% endfor %}
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>My Account</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- MY-ACCOUNT-AREA START -->

													<form method='post'>
                                                        {%csrf_token%}
                                                        {{bbf.as_p}}
                                                        <button type="submit" data-text="save" class="button-one submit-button mt-15">save</button>
                                                    </form>	
												
						
			<footer>
				{% endblock content %}
				

mysite/bboard/templates/main/users/change_user.html
{% extends 'layout/basic.html' %}
{% block title %}Change || Hurst {%endblock title%}
{% block content %}



			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Change</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Change</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_authenticated %}

			    <h1></h1>
                <div class="login-area  pt-80 pb-80">
                    <div class="container">
                        <form action="#">	
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="customer-login text-left">
                                        <h4 class="title-1 title-border text-uppercase mb-30">Change</h4>
                                        <form method='post'>
                                            {% csrf_token %}
                                            {{form.as_p}}
                                            <button type="submit" data-text="login" class="button-one submit-button mt-15">change</button>
                                        </form>
                                    </div>					
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/users/drop_password.html
{% extends 'layout/basic.html' %}
{% block title %}Change || Hurst {%endblock title%}
{% block content %}



			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Drop password</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Drop password</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_authenticated %}
            
			    <h1></h1>
                <div class="login-area  pt-80 pb-80">
                    <div class="container">
                        <form action="#">	
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="customer-login text-left">
                                        <h4 class="title-1 title-border text-uppercase mb-30">Drop</h4>
                                        <form method='post'>
                                            {% csrf_token %}
                                            {{form.as_p}}
                                            <button type="submit" data-text="login" class="button-one submit-button mt-15">Drop</button>
                                        </form>
                                    </div>					
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/users/login.html
{% extends 'layout/basic.html' %}
{% block title %}Login  || Hurst {%endblock title%}
{% block content %}



			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Login</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Sing In</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_authenticated %}

			    <h1>You are already signed in.</h1>
			{%else%}
			<div class="login-area  pt-80 pb-80">
				<div class="container">
						<div class="row">
							<div class="col-lg-12">
								<div class="customer-login text-left">
									<h4 class="title-1 title-border text-uppercase mb-30">Sign in or <a href="{% url 'bboard:register' %}"><u>Register</u></a></h4> 
									<p class="text-gray">If you have an account with us, Please login!</p>
									<form method="post">
										{% csrf_token %}
										{{form.as_p}}
										
										

										<button type="submit" data-text="login" class="button-one submit-button mt-15">login</button>
									</form>
									<p><a href="{% url 'bboard:drop' %}" class="text-gray">Forget your password?</a></p>
								</div>					
							</div>
							
							
						</div>
				</div>
			</div>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/users/profile.html
{% extends 'layout/basic.html' %}
{% block title %} My Account || Hurst {% endblock title %}

{% block content %}
			<!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								{% for b in bb %}
								<div class="heading-banner-title">
									<h2>My Account</h2>
								</div>
								{% endfor %}
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>My Account</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- MY-ACCOUNT-AREA START -->
			<div class="my-account-area  pt-80 pb-80">
				<div class="container">	
					<div class="my-account">
						<div class="row">
							<div class="col-md-6">
								<div class="panel-group" id="accordion">
									
									<div class="panel mb-2">
										<div class="my-account-menu">
											<a class="collapsed"  data-bs-toggle="collapse"  href="#my-billing">
											My Billing address
											</a>
										</div>
										{% for b in bb %}
										<div id="my-billing" class="panel-collapse collapse" data-bs-parent="#accordion">
											<div class="panel-body">
												<div class="billing-details shop-cart-table">
													<h4>Name: {{b.name}}</h2>
													<h4>Phone: {{b.phoneNumber}}</h2>
													<h4>Index : {{b.indexxx}}</h2>
													<h4>Address: {{b.address}}</h2>
                                                    
													
														
												</div>
												{% endfor %}
																						<hr><h2><button ><a href="{% url 'bboard:billing' %}">Edit</a></button></h2><hr>
											</div>
										</div>
										

									</div>
									<div class="panel mb-2 mb-md-0">
										<div class="my-account-menu">
											<a class="collapsed"  data-bs-toggle="collapse"  href="#my-order">
											Order history and details
											</a>
										</div>
										<div id="my-order" class="panel-collapse collapse" data-bs-parent="#accordion">
											<div class="panel-body">
												<div class="our-order payment-details shop-cart-table">
													<table>
														
												
												
												
														<thead>
															<tr>
																<th><strong>Product</strong></th>
																<th class="text-end"><strong>Total</strong></th>
															</tr>
														</thead>
														{% for item in cart %}
											    {% with product=item.product %}
														<tbody>
															<tr>
																<td>{{product.name}}  x {{ item.quantity }}</td>
																<td class="text-end">${{item.total_price}}</td>
															</tr>
															{%endwith%}
														{% endfor %}
															<tr>
																<td>Order Total</td>
																<td class="text-end">${{cart.get_total_price}}</td>
															</tr>
														</tbody>
														
													</table>
												</div>
											</div>
										</div>
									</div>					
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>
			<!-- MY-ACCOUNT-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
				{% endblock content %}
				

mysite/bboard/templates/main/users/register.html
{% extends 'layout/basic.html' %}
{% block title %}Register  || Hurst {%endblock title%}
{% block content %}



			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Register</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Register</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_authenticated %}

			    <h1>You are already signed in.</h1>
			{%else%}
			<div class="login-area  pt-80 pb-80">
				<div class="container">
						<div class="row">
							
							<div class="col-lg-6">
								<div class="customer-login text-left">
									<form method='post'>
										{%csrf_token%}
										<h4 class="title-1 title-border text-uppercase mb-30">Register</h4>
										<p class="text-gray">If you have an account with us, <a href="{% url 'bboard:login' %}"><u>Please Login</u></a></p>
							
										{{form.as_p}}
										<button type="submit" data-text="regiter" class="button-one submit-button mt-15">register</button>
								    </form>
								</div>					
							</div>
						</div>
				</div>
			</div>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/users/register_activate.html
{% extends 'layout/basic.html' %}
{% block title %}Register  || Hurst {%endblock title%}
{% block content %}



			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_authenticated %}

			    <h1>You are already signed in.</h1>
			{%else%}
			<div class="login-area  pt-80 pb-80">
				<div class="container">
						<div class="row">
							
							<div class="col-lg-6">
								<div class="customer-login text-left">
									<h1>Good!!!</h1>
								</div>					
							</div>
						</div>
				</div>
			</div>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/users/register_bed.html
{% extends 'layout/basic.html' %}
{% block title %}Register  || Hurst {%endblock title%}
{% block content %}



			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_authenticated %}

			    <h1>You are already signed in.</h1>
			{%else%}
			<div class="login-area  pt-80 pb-80">
				<div class="container">
						<div class="row">
							
							<div class="col-lg-6">
								<div class="customer-login text-left">
									<h1>No Good!!!</h1>
								</div>					
							</div>
						</div>
				</div>
			</div>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/users/register_don.html
{% extends 'layout/basic.html' %}
{% block title %}Register  || Hurst {%endblock title%}
{% block content %}



			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Register</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Register</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_authenticated %}

			    <h1>You are already signed in.</h1>
			{%else%}
			<div class="login-area  pt-80 pb-80">
				<div class="container">
						<div class="row">
							
							<div class="col-lg-6">
								<div class="customer-login text-left">
									<h1>Email send</h1>
								</div>					
							</div>
						</div>
				</div>
			</div>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}

mysite/bboard/templates/main/users/sendler.html
{% extends 'layout/basic.html' %}
{% block title %}Sendler || Hurst {%endblock title%}
{% block content %}



			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Sendler</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="{% url 'bboard:index' %}">Home</a></li>
										<li>Sendler</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- SHOPPING-CART-AREA START -->
			{% if user.is_superuser %}

			    
				<div class="login-area  pt-80 pb-80">
					<div class="container">
							<div class="row">
								<div class="col-lg-12">
									<div class="customer-login text-left">
										
										<form method="post">
											{% csrf_token %}
											{{csc_form.as_p}}
											
											
	
											<button type="submit" data-text="send" class="button-one submit-button mt-15">send</button>
										</form>

									</div>					
								</div>
								
								
							</div>
					</div>
				</div>
			{%else%}
			<h1>Poshel naxyi</h1>
			{%endif%}
			<!-- SHOPPING-CART-AREA END -->
			<!-- FOOTER START -->
			<footer>
{% endblock content %}